kafka:
  brokers:
    - localhost:9092
  topic:
    name: cdc-events
    partitions: 1
  retry:
    max: 5
    backoff: 100 #ms
  consumer_group: "flexprice-consumer-local"

opensearch:
  urls:
    - http://localhost:9200
  username: admin
  password: admin
  max_retries: 5
  index:
    name: cdc-events
    buff_size: 100
    flush_interval: 5 # seconds
